version: '3.9'

services:
  sbrp-db:
    image: mysql:8.0.34
    platform: linux/x86_64
    volumes:
      - mysql_data:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=fwogportal
      - MYSQL_USER=fwogking
      - MYSQL_PASSWORD=fwogp4ssw0rd
      - MYSQL_ROOT_PASSWORD=fwogp4ssw0rd
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ufwogking", "-pfwogp4ssw0rd"]
      interval: 10s
      timeout: 5s
      retries: 5

  sbrp-backend:
    build: ./src
    command: bash -c 'while !</dev/tcp/sbrp-db/3306; do sleep 1; done; uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8003:8000
    environment:
      - DATABASE_URL=mysql+pymysql://fwogking:fwogp4ssw0rd@sbrp-db/fwogportal
    depends_on:
      sbrp-db:
        condition: service_healthy

  # sbrp-test:
  #   build: ./src
  #   command: bash -c 'while !</dev/tcp/sbrp-db/3306; do sleep 1; done; python -m pytest'
  #   volumes:
  #     - ./src/:/usr/src/app/
  #   environment:
  #     - DATABASE_URL=mysql+pymysql://fwogking:fwogp4ssw0rd@sbrp-db/fwogportal
  #   depends_on:
  #     sbrp-db:
  #       condition: service_healthy

volumes:
  mysql_data: