name: frontend testing with jest
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: frontend
    
jobs:
  run-frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install node dependencies
        run: npm i 
      - name: Run jest tests
        run: npm run test
